// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (name)
VALUES ($1)
RETURNING id, name
`

func (q *Queries) CreateItem(ctx context.Context, name string) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem, name)
	var i Item
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, name
  FROM items
 WHERE id = $1
`

func (q *Queries) GetItemByID(ctx context.Context, id int32) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemByID, id)
	var i Item
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
