services:
  repository:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        SERVICE: repository
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
