services:
  ingestor:
    build:
      context: .
      dockerfile: ./ingestor/Dockerfile
    ports:
      - "${INGESTOR_PORT:-8080}:8080"
    depends_on:
      context:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - CONTEXT_SERVICE_URL=http://context:${CONTEXT_PORT:-8081}/input
      - INGESTOR_PORT=8080
  
  context:
    build:
      context: .
      dockerfile: ./context/Dockerfile
    ports:
      - "${CONTEXT_PORT:-8081}:8081"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${CONTEXT_PORT:-8081}/health || (echo 'Health check failed' && exit 1)"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    environment:
      - CONTEXT_PORT=8081
      - CONTEXT_HOST=0.0.0.0 # Use Docker Compose namespace-compatible host

networks:
  app-network:
    driver: bridge
