services:
  ingestor:
    build:
      context: .
      dockerfile: ./ingestor/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - context
    networks:
      - app-network
    environment:
      - CONTEXT_SERVICE_URL=http://context:8081  # Correctly point to the context service
      - INGESTOR_PORT=8080
      - REMEDIATIONS_SERVICE_URL=http://remediations:8082  # Add URL for remediations service
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  context:
    build:
      context: .
      dockerfile: ./context/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -s -o /dev/null -w '%{http_code}' http://localhost:8081/health | grep -q 200 || (echo 'Health check failed' && exit 1)"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s
    environment:
      - CONTEXT_PORT=8081
      - CONTEXT_HOST=0.0.0.0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  remediations:
    build:
      context: .
      dockerfile: ./remediations/Dockerfile
    ports:
      - "8082:8082"
    networks:
      - app-network
    environment:
      - REMEDIATIONS_PORT=8082
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge
