version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: local_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "127.0.0.1:5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: local_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672" # Management UI
