services:
  ingestor:
    build:
      context: .
      dockerfile: ./ingestor/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      remediations:
        condition: service_healthy
      context:
        condition: service_healthy
      orthos:
        condition: service_healthy
      workserver:
        condition: service_healthy
      jaeger:
        condition: service_started
      otel-collector:
        condition: service_started
      pyroscope:
        condition: service_started
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "Accept: application/json", "http://localhost:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s
    environment:
      - INGESTOR_SERVICE_NAME=ingestor
      - INGESTOR_CONTEXT_SERVICE_URL=http://context:8081
      - INGESTOR_PORT=8080
      - INGESTOR_REMEDIATIONS_SERVICE_URL=http://remediations:8082
      - INGESTOR_ORTHOS_SERVICE_URL=http://orthos:8083
      - INGESTOR_WORK_SERVER_URL=http://workserver:8084
      - INGESTOR_JAEGER_ENDPOINT=jaeger:4317
      - INGESTOR_METRICS_ENDPOINT=otel-collector:4317
      - INGESTOR_PYROSCOPE_ENDPOINT=http://pyroscope:4040
      - INGESTOR_HOST=0.0.0.0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  context:
    build:
      context: .
      dockerfile: ./context/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - jaeger
      - otel-collector
      - pyroscope
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "Accept: application/json", "http://localhost:8081/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s
    environment:
      - CONTEXT_SERVICE_NAME=context
      - CONTEXT_PORT=8081
      - CONTEXT_HOST=0.0.0.0
      - CONTEXT_JAEGER_ENDPOINT=jaeger:4317
      - CONTEXT_METRICS_ENDPOINT=otel-collector:4317
      - CONTEXT_PYROSCOPE_ENDPOINT=http://pyroscope:4040
      # Database configuration options:
      # 1. In-memory database (no persistence)
      - "CONTEXT_LIBSQL_ENDPOINT=:memory:"
      
      # 2. Local SQLite file (persistence with Docker volume)
      # - "CONTEXT_LIBSQL_ENDPOINT=/data/context.db"
      
      # 3. Embedded replica with sync to remote Turso database
      # - "CONTEXT_LIBSQL_ENDPOINT=/data/context.db|https://your-db-url.turso.io|your-auth-token"
      
      # 4. Embedded replica with sync to remote database (no auth)
      # - "CONTEXT_LIBSQL_ENDPOINT=/data/context.db|https://your-db-url.turso.io|none"
    volumes:
      - context-data:/data  # For persistent storage
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  remediations:
    build:
      context: .
      dockerfile: ./remediations/Dockerfile
    ports:
      - "8082:8082"
    networks:
      - app-network
    depends_on:
      - jaeger
      - otel-collector
      - pyroscope
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "Accept: application/json", "http://localhost:8082/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s
    environment:
      - REMEDIATIONS_SERVICE_NAME=remediations
      - REMEDIATIONS_PORT=8082
      - REMEDIATIONS_HOST=0.0.0.0
      - REMEDIATIONS_JAEGER_ENDPOINT=jaeger:4317
      - REMEDIATIONS_METRICS_ENDPOINT=otel-collector:4317
      - REMEDIATIONS_PYROSCOPE_ENDPOINT=http://pyroscope:4040
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  orthos:
    build:
      context: .
      dockerfile: ./orthos/Dockerfile
    ports:
      - "8083:8083"
    networks:
      - app-network
    depends_on:
      - jaeger
      - otel-collector
      - pyroscope
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "Accept: application/json", "http://localhost:8083/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s
    environment:
      - ORTHOS_SERVICE_NAME=orthos
      - ORTHOS_PORT=8083
      - ORTHOS_HOST=0.0.0.0
      - ORTHOS_JAEGER_ENDPOINT=jaeger:4317
      - ORTHOS_METRICS_ENDPOINT=otel-collector:4317
      - ORTHOS_PYROSCOPE_ENDPOINT=http://pyroscope:4040
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  workserver:
    build:
      context: .
      dockerfile: ./workserver/Dockerfile
    ports:
      - "8084:8084"
    networks:
      - app-network
    depends_on:
      - jaeger
      - otel-collector
      - pyroscope
      - orthos
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "Accept: application/json", "http://localhost:8084/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s
    environment:
      - WORKSERVER_SERVICE_NAME=workserver
      - WORKSERVER_PORT=8084
      - WORKSERVER_HOST=0.0.0.0
      - WORKSERVER_JAEGER_ENDPOINT=jaeger:4317
      - WORKSERVER_METRICS_ENDPOINT=otel-collector:4317
      - WORKSERVER_PYROSCOPE_ENDPOINT=http://pyroscope:4040
      - WORKSERVER_REQUEUE_TIMEOUT_SECONDS=300
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  search:
    build:
      context: .
      dockerfile: ./search/Dockerfile
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    ports:
      - "8085"  # Only specify container port to allow Docker to allocate ports dynamically
    networks:
      - app-network
    depends_on:
      - jaeger
      - otel-collector
      - pyroscope
      - orthos
      - remediations
      - context
      - workserver
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "Accept: application/json", "http://localhost:8085/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s
    environment:
      - SEARCH_SERVICE_NAME=search
      - SEARCH_PORT=8085
      - SEARCH_HOST=0.0.0.0
      - SEARCH_JAEGER_ENDPOINT=jaeger:4317
      - SEARCH_METRICS_ENDPOINT=otel-collector:4317
      - SEARCH_PYROSCOPE_ENDPOINT=http://pyroscope:4040
      - SEARCH_ORTHOS_SERVICE_URL=http://orthos:8083
      - SEARCH_REMEDIATIONS_SERVICE_URL=http://remediations:8082
      - SEARCH_CONTEXT_SERVICE_URL=http://context:8081
      - SEARCH_WORK_SERVER_URL=http://workserver:8084
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: always
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"   # accept jaeger.thrift over compact thrift protocol
      - "6832:6832/udp"   # accept jaeger.thrift over binary thrift protocol
      - "5778:5778"       # serve configs
      - "16686:16686"     # serve frontend
      - "14268:14268"     # accept jaeger.thrift directly from clients
      - "14250:14250"     # accept model.proto
      - "4317:4317"       # OTLP gRPC endpoint
      - "4318:4318"       # OTLP HTTP endpoint
    networks:
      - app-network
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: always

  pyroscope:
    image: pyroscope/pyroscope:latest
    ports:
      - "4040:4040"  # Pyroscope UI
    networks:
      - app-network
    volumes:
      - pyroscope-data:/var/lib/pyroscope
    environment:
      - PYROSCOPE_LOG_LEVEL=debug
      - PYROSCOPE_RETENTION=24h  # Retain data for 24 hours for better visibility
      - PYROSCOPE_STORAGE_PATH=/var/lib/pyroscope/data
      - PYROSCOPE_BADGER_NO_TRUNCATE=true
      - PYROSCOPE_MAX_NODES_SERIALIZATION=2048  # Increase max nodes for better flamegraph detail
      - PYROSCOPE_MAX_NODENAME_LENGTH=4096  # Allow longer function names
    restart: always
    command:
      - "server"
      
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4319:4317"   # OTLP gRPC receiver (changed from 4317 to avoid conflict)
      - "4320:4318"   # OTLP http receiver (changed from 4318 to avoid conflict)
      - "55679:55679" # zpages extension
    networks:
      - app-network
    restart: always

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - app-network
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_LOG_LEVEL=debug
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    restart: always

volumes:
  pyroscope-data:
  context-data:  # For persistent storage
  rabbitmq-data:  # Added for RabbitMQ data persistence

networks:
  app-network:
    driver: bridge
