global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889']
        labels:
          group: 'otel-collector'

  # Comment out the duplicate scrape job for search service metrics via otel-collector
  # - job_name: 'crochet-services'
  #   scrape_interval: 10s
  #   static_configs:
  #     - targets: ['otel-collector:8889']
  #       labels:
  #         group: 'crochet-services'

  - job_name: 'rabbitmq-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['rabbitmq-exporter:9419']
        labels:
          service: 'rabbitmq'

  - job_name: 'workserver'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8084']
        labels:
          service: 'workserver'

  - job_name: 'orthos'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          service: 'orthos'

  - job_name: 'search'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8085', 'search:8085']
        labels:
          service: 'search'

  - job_name: 'remediations'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          service: 'remediations'