// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	db "crochet/pkg/db"

	mock "github.com/stretchr/testify/mock"
)

// QueriesInterface is an autogenerated mock type for the QueriesInterface type
type QueriesInterface struct {
	mock.Mock
}

// CreateItem provides a mock function with given fields: ctx, name
func (_m *QueriesInterface) CreateItem(ctx context.Context, name string) (db.Item, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateItem")
	}

	var r0 db.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (db.Item, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) db.Item); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(db.Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetItemByID provides a mock function with given fields: ctx, id
func (_m *QueriesInterface) GetItemByID(ctx context.Context, id int32) (db.Item, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetItemByID")
	}

	var r0 db.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (db.Item, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) db.Item); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.Item)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewQueriesInterface creates a new instance of QueriesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueriesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueriesInterface {
	mock := &QueriesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
