// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	amqp091 "github.com/rabbitmq/amqp091-go"

	mock "github.com/stretchr/testify/mock"
)

// Queue is an autogenerated mock type for the Queue type
type Queue struct {
	mock.Mock
}

// ConsumeOne provides a mock function with given fields: ctx, ch, queueName
func (_m *Queue) ConsumeOne(ctx context.Context, ch *amqp091.Channel, queueName string) (*amqp091.Delivery, error) {
	ret := _m.Called(ctx, ch, queueName)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeOne")
	}

	var r0 *amqp091.Delivery
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *amqp091.Channel, string) (*amqp091.Delivery, error)); ok {
		return rf(ctx, ch, queueName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *amqp091.Channel, string) *amqp091.Delivery); ok {
		r0 = rf(ctx, ch, queueName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*amqp091.Delivery)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *amqp091.Channel, string) error); ok {
		r1 = rf(ctx, ch, queueName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateChannel provides a mock function with no fields
func (_m *Queue) CreateChannel() (*amqp091.Channel, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateChannel")
	}

	var r0 *amqp091.Channel
	var r1 error
	if rf, ok := ret.Get(0).(func() (*amqp091.Channel, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *amqp091.Channel); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*amqp091.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Publish provides a mock function with given fields: ctx, ch, queueName, body
func (_m *Queue) Publish(ctx context.Context, ch *amqp091.Channel, queueName string, body []byte) error {
	ret := _m.Called(ctx, ch, queueName, body)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *amqp091.Channel, string, []byte) error); ok {
		r0 = rf(ctx, ch, queueName, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewQueue creates a new instance of Queue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *Queue {
	mock := &Queue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
