services:
  ingestor:
    build:
      context: .
      dockerfile: ./ingestor/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      context:
        condition: service_healthy
    networks:
      - app-network
  
  context:
    build:
      context: .
      dockerfile: ./context/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/health || (echo 'Health check failed' && exit 1)"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    environment:
      - "HOST=0.0.0.0" # Ensure the service binds to all interfaces

networks:
  app-network:
    driver: bridge
